resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/webdev/flight-school
    branch: master

jobs:
- name: tests
  plan:
  - get: flight-school
    trigger: true
  - aggregate:
    - task: rspec_tests
      file: flight-school/build.yml
    - task: cucumber_tests
      file: flight-school/build.yml
